In [1]:
import os
import pandas as pd
import numpy as np
import nibabel as nib

from sklearn.model_selection import train_test_split

from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Dropout, Flatten, Activation, Conv3D, MaxPooling3D

In [2]:
hgg_img_data_train = []
counter = 0

for file in os.listdir('./data/bet_processed/'):
    if file.endswith('.nii.gz'):
        file_path = './data/bet_processed/' + file
        img = nib.load(file_path)
        array_flat = img.get_data() / 255
        hgg_img_data_train.append(array_flat)
        
        counter += 1
        if counter%100 == 0:
            print(f"{counter} out of {len(os.listdir('./data/bet_processed/'))-1}")

100 out of 1032
200 out of 1032
300 out of 1032
400 out of 1032
500 out of 1032
600 out of 1032
700 out of 1032
800 out of 1032
900 out of 1032
1000 out of 1032


In [3]:
hgg_y = np.ones(shape=len(hgg_img_data_train), dtype=int)

In [4]:
hgg_y

array([1, 1, 1, ..., 1, 1, 1])

In [5]:
lgg_img_data_train = []
counter = 0

for file in os.listdir('./data/lgg_bet_processed/'):
    if file.endswith('.nii.gz'):
        file_path = './data/lgg_bet_processed/' + file
        img = nib.load(file_path)
        array_flat = img.get_data() / 255
        lgg_img_data_train.append(array_flat)
        
        counter += 1
        if counter%100 == 0:
            print(f"{counter} out of {len(os.listdir('./data/lgg_bet_processed/'))-1}")

100 out of 303
200 out of 303
300 out of 303


In [6]:
lgg_y = np.zeros(shape=len(lgg_img_data_train), dtype=int)

In [7]:
X = np.array(hgg_img_data_train + lgg_img_data_train)

In [8]:
y = np.array(list(hgg_y) + list(lgg_y))

In [9]:
# % of Data that's Target: 1
sum(y) / len(y)

0.7724550898203593

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                   stratify=y)

In [35]:
X_train.shape

(240, 240, 155)

In [40]:
np.array(X_train).shape

(1002, 240, 240, 155)

In [ ]:
X

In [43]:
# REALLY BASIC 3D-CNN JUST TO SEE

cnn = Sequential()

cnn.add(Conv3D(
    filters=6,
    kernel_size=(3,3,3), # height/width of filter
    activation='relu',
    input_shape=(240, 240, 155, 1)))

cnn.add(MaxPooling3D(
    pool_size=(2,2,2)
))

cnn.add(Conv3D(
    filters= 16,
    kernel_size= (3,3,3),
    activation='relu'
))

cnn.add(MaxPooling3D(
    pool_size=(2,2,2)
))

cnn.add(Flatten())

cnn.add(Dense(
    units=128,
    activation='relu'
))

# Output Layer
cnn.add(Dense(
    units=2,
    activation='softmax'
))

cnn.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [ ]:
history = cnn.fit(np.array(X_train), y_train,
                 batch_size=512,
                 validation_data=(np.array(X_test), y_test),
                 epochs=5,
                 verbose=2)

In [63]:
test = np.ones(10)

In [64]:
test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
test/10

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [38]:
test_train = []
counter = 0

for file in os.listdir('./data/bet_processed/')[:5]:
    if file.endswith('.nii.gz'):
        file_path = './data/bet_processed/' + file
        img = nib.load(file_path)
        array_flat = img.get_data() / 0
        print(array_flat)
#         test_train.append(array_flat)
        
#         counter += 1
#         if counter%100 == 0:
#             print(f"{counter} out of {len(os.listdir('./data/bet_processed/')[:5])-1}")

/Users/Work/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  
/Users/Work/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in true_divide
  


[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  ...
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  ...
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  ...
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 ...

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  ...
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]

 [[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  ...
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan n